### PR TITLE
Fix Token Transformer references on typography and boxshadow tokens

### LINKED ISSUE #685: Token Transformer doesn't preserve references on typography and boxshadow tokens
**Describe the bug**
When setting the `--resolveReferences` param to `false` or `'math'` the references are kept accordingly on simple/flat token values, but not on composite/complex/nested typography and boxshadow tokens (as well as boxshadow[] arrays).

**To Reproduce**
1. Include typography or boxshadow tokens with references and/or math expressions in the composite/nested values.
2. Run token-transformer cli with `--resolveReferences` param set to `false` or `'math'`
3. See references are resolved to their values and not kept in the output json.

**Expected behavior**
I would expect references/aliases are kept in the output of composite/complex/nested typography and boxshadow tokens.

**JSON (optional)**
```JSON
{
  "name": "typography.h1",
  "type": "typography",
  "value": {
    "fontFamily": "Roboto",
    "fontSize": "{text.size.base}",
    "fontWeight": "{text.fontWeight.light}",
}
```

### LINKED ISSUE #690: Token Transformer doesn't preserve references on tokens inside css functions or list values
**Describe the bug**
When setting the `--resolveReferences` param to `false` or `'math'` the references are NOT kept in the output when inside:
- **CSS functions**, e.g. `calc({token} * 2)`, `rgba(255, 0, 0, {token})`, `drop-shadow(1rem 0 1rem {token})` etc.
- **CSS properties with a list of values**, e.g. `box-shadow: 10px 5px 5px {token}`, `border-radius: 10% 20% 30% {token}` etc. 

**To Reproduce**
1. Include tokens with references inside a CSS function or a CSS property with a list of values (see above).
2. Run token-transformer cli with `--resolveReferences` param set to `false` or `'math'`
3. See references are resolved to their values and not kept in the output json.

**Expected behavior**
I would expect references/aliases are kept in the output of tokens also for CSS functions and CSS properties with a list of values.

**JSON (optional)**
```JSON
{
  "medium-shadow": {
    "value": {
      "x": "0",
      "y": "4",
      "blur": "8",
      "spread": "0",
      "color": "rgba(255, 0, 0, {opacity.low})",
      "type": "dropShadow"
    },
    "type": "boxShadow"
  },
  "button-radius": {
    "value": "border-radius: 20% {border-radius.smooth} {border-radius.smooth} 20%",
    "type": "borderRadius"
  },
  "my-space": {
    "value": "calc({spacing.xl} * 2)",
    "type": "spacing"
  }
}
```

### PR DESCRIPTION
**Pull request by jakobe**
Closes #685, closes #690

### CODE REVIEW

**Comment by jakobe** [comment]
@six7 I'm guessing the storybook deployment fails because of a missing token (pun intended 😋 ) when running from my branch/PR, right? Other than that, I hope the build and tests are good 🤞🏻

**Review by LiamMartens — APPROVED** [review]

**Comment by six7** [comment]
> @six7 I'm guessing the storybook deployment fails because of a missing token (pun intended 😋 ) when running from my branch/PR, right? Other than that, I hope the build and tests are good 🤞🏻

yes, that one fails because storybook is part of the `next` branch. i'm currently preparing for the next release, so i'll have to leave this one open until we have that done, but will do that afterwards 👍

**Comment by jakobe** [comment]
> > @six7 I'm guessing the storybook deployment fails because of a missing token (pun intended 😋 ) when running from my branch/PR, right? Other than that, I hope the build and tests are good 🤞🏻
> 
> yes, that one fails because storybook is part of the `next` branch. i'm currently preparing for the next release, so i'll have to leave this one open until we have that done, but will do that afterwards 👍

@six7 Thx 👍🏻 
I've merged latest changes from `main` to my branch, and I see now, that the SB deployment goes through, but the Cypress test fails. As far as I can see that's not related to my changes or...?

> `AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-cy="themeselector-dropdown"]`, but never found it.`

**Comment by jakobe** [comment]
@six7 Any updates on this one? 🙏🏻 😊

**Review by six7 — APPROVED** [review]

**Comment by six7** [comment]
Sorry for the delay. Merging this in now and releasing tomorrow morning 🙏

**Comment by jakobe** [comment]
> Sorry for the delay. Merging this in now and releasing tomorrow morning 🙏

No worries, thx 😊👍🏻

**Comment by six7** [comment]
> > Sorry for the delay. Merging this in now and releasing tomorrow morning 🙏
> 
> No worries, thx 😊👍🏻

Released ! 🎉 Thanks again!

**Pull request merged**
