### PR TITLE
fix sync styles

### PR DESCRIPTION
**Pull request by swordEdge**
https://www.loom.com/share/2820c621b48849c6b89404716a6269f9

### CODE REVIEW

**Review by LiamMartens — APPROVED** [review]

**Comment by LiamMartens** [comment]
@swordEdge just tests

**Review by six7 — CHANGES_REQUESTED** [review]
@swordEdge this approach doesn't work. We cannot just remove and then recreate the style. This will break any connection the user had with that style.

We need to rename the style properly

https://user-images.githubusercontent.com/4548309/197030286-743a6949-5693-47e9-bb6a-cb13e79b143c.mp4

**Comment by swordEdge** [comment]
> @swordEdge this approach doesn't work. We cannot just remove and then recreate the style. This will break any connection the user had with that style.
> 
> We need to rename the style properly

@six7  It seems like that there is no way just rename the style. ???

**Comment by six7** [comment]
Works! Can you fix tests and coverage? Then let's get this merged in 🚀

**Pull request merged**
