### PR TITLE
feat: typescript build

### PR DESCRIPTION
**Pull request by LiamMartens**
@six7 needs a good functional test. I did update the webpack config to fail when encountering typing errors. So from this point on once ready/merged we should always have a completely typed codebase.

### CODE REVIEW

**Comment by six7** [comment]
> @six7 needs a good functional test. I did update the webpack config to fail when encountering typing errors. So from this point on once ready/merged we should always have a completely typed codebase.

currently for us it fails to launch the plugin (and there's a failing test)

**Comment by mikekamminga** [comment]
Steps:
- add JSONBin sync
- Create new tokens set
- sync (worked)
- add new color token
- Sync
- Edit token
- ERROR

image

**From the console**
Uncaught TypeError: value.replace is not a function
    at <anonymous>:29813:87
    at mountMemo (<anonymous>:125844:19)
    at Object.useMemo (<anonymous>:126217:16)
    at useMemo (<anonymous>:146320:21)
    at DownshiftInput (<anonymous>:29812:69)
    at renderWithHooks (<anonymous>:124983:18)
    at mountIndeterminateComponent (<anonymous>:127809:13)
    at beginWork (<anonymous>:129047:16)
    at HTMLUnknownElement.callCallback (<anonymous>:113951:14)
    at HTMLUnknownElement.sentryWrapped (<anonymous>:17930:23)
    at Object.invokeGuardedCallbackDev (<anonymous>:114000:16)
    at invokeGuardedCallback (<anonymous>:114062:31)
    at beginWork$1 (<anonymous>:133957:7)
    at performUnitOfWork (<anonymous>:132772:12)
    at workLoopSync (<anonymous>:132700:5)
    at renderRootSync (<anonymous>:132663:7)
    at performSyncWorkOnRoot (<anonymous>:132286:18)
    at <anonymous>:121325:26
    at unstable_runWithPriority (<anonymous>:149922:12)
    at runWithPriority$1 (<anonymous>:121274:10)
    at flushSyncCallbackQueueImpl (<anonymous>:121320:9)
    at flushSyncCallbackQueue (<anonymous>:121307:3)
    at discreteUpdates$1 (<anonymous>:132413:9)
    at discreteUpdates (<anonymous>:113762:12)
    at dispatchDiscreteEvent (<anonymous>:115887:3)
    at HTMLBodyElement.sentryWrapped (<anonymous>:17930:23)

After restart, plugin doesn't open, in console:
[LaunchDarkly] network error (NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://app.launchdarkly.com/sdk/evalx/626fb05d52e5c715abd11b5e/users/eyJrZXkiOiIxMDQ4MjcwMTk4NDY0NjM5ODgxIiwiY3VzdG9tIjp7InBsYW4iOiIiLCJlbWFpbCI6IiIsIm9zIjp0cnVlfX0': Document is already detached.)

**Comment by LiamMartens** [comment]
@mikekamminga you are right - the error was introduced while merging in the `next` changes.

**Comment by six7** [comment]
- Settings: Can't select Local document anymore
image


- Settings: All sync providers seem to be active at the same time
image

- Having Git sync and having local changes no longer, restarting the plugin no longer asks the user if they want to Pull or keep their local changes (we introduced this recently on the next branch but seems to have been broken now)

- GitHub sync: Pushing to GitHub seems to have been broken. Console says `Buffer is not defined`

**Comment by LiamMartens** [comment]
@six7 thanks for testing
- I tested the selecting of local document. This appears to work as expected compared to the live plugin. I can confirm it doesn't re-select LOCAL if LOCAL is already selected as the storage type (but you have selected another credential type to edit)
- I fixed the annotation placement
- I looked at the typography editor - I can't seem to reproduce the issue with the auto suggest opening by default. I tried by editing and by creating new tokens.
- The provider active status is fixed
- The new git "Ask to pull" is fixed, something went missing during the merge
- The Buffer error is also fixed. This was introduced because I properly upgraded to Webpack 5. It looks like we were still using Webpack 4 up until now due to multiple versions being installed. Webpack 5 drops the buffer polyfil by default so I had to manually enable it.

**Comment by six7** [comment]
> * I looked at the typography editor - I can't seem to reproduce the issue with the auto suggest opening by default. I tried by editing and by creating new tokens.

You can load the preset and then edit one of the typography tokens to see the bug in action


https://user-images.githubusercontent.com/4548309/169469319-03d3aced-38ab-4691-affa-4a95df670853.mp4

## Other bugs
- Launching the plugin in a new file results in endless Loading screen
- The bug with Local changes is not fixed quite yet. It doesn't give me the popup when I was on GitHub storage and had local changes (I noticed it has this bug when you press the `Update` button, if you dont press that it works fine). It also seems to now ask when storage is set to `Local` and you have changes if you'd like to "Pull from Local" which seems to be a regression. There's no pulling on Local storage as the local storage is always the source of truth. This should ask you only when you have local changes that weren't pushed yet to the repository. See video


https://user-images.githubusercontent.com/4548309/169470623-a2dc2fae-af58-44a3-adee-ff0335fb8773.mp4


- Updating or adding token descriptions doesn't work currently (tried on different token types, happened on all of them)

**Comment by LiamMartens** [comment]
@six7 I was just doing some test and it looks like all the bugs you mentioned (aside from the description update) are also present on the `next` branch currently. Shall we fix these in a different branch? (I did fix the description update)

**Comment by six7** [comment]
> @six7 I was just doing some test and it looks like all the bugs you mentioned (aside from the description update) are also present on the `next` branch currently. Shall we fix these in a different branch? (I did fix the description update)

You're right. I created new issues to tackle these.

From my end this is working functionally. @esthercheran @mikekamminga anything you noticed? Otherwise let's merge it in.

**Comment by LiamMartens** [comment]
@six7 yea would love to get this merged in so we can move forward type safe with all further branches

**Comment by six7** [comment]
Got it, from my end we can merge it in 👍

**Review by six7 — APPROVED** [review]

**Pull request merged**
