### PR TITLE
Fix/gitlab remove tokenset and duplicate

### LINKED ISSUE #1006: Renaming a token group name in a duplicated token set renames in the original set as well
**Describe the bug**
Renaming a token group name in a duplicated token set renames in the original set as well

**To Reproduce**
1. Duplicate a token set and rename it 
2. On the Duplicated token set, rename a token group
3. Check the original token set
4. The token group in the original token set is also renamed

**Expected behavior**
The token group in the original token set should not be affected by the renaming in the duplicated token set.

**Screenshots or Screencasts**

https://user-images.githubusercontent.com/66366384/178239522-b88d1119-6fbc-475c-a2f0-c7ce5657f5df.mov

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

### PR DESCRIPTION
**Pull request by LiamMartens**
Fixes #1006 

- [x]  functional review: @esthercheran

### CODE REVIEW

**Comment by LiamMartens** [comment]
@esthercheran this contains the fix for the mutlifile push in Gitlab and the duplicate + rename issue. Let's test this before release of course; also wondering if we should provide a beta package to verify this fix because the issue is very specific.

**Comment by six7** [comment]
@esthercheran can you functionally review this? I'm not aware of what to look for when reviewing this.

**Comment by esthercheran** [comment]
@LiamMartens @six7 I think we should release a beta as the Gitlab push issue is very specific to the commit message rule. I have tested the other functionality, it is working fine.

**Comment by LiamMartens** [comment]
This also fixes #1006

**Comment by LiamMartens** [comment]
@six7 @esthercheran checked this with the user in the figma tokens slack

**Review by six7 — APPROVED** [review]

**Pull request merged**
