### PR TITLE
1182-token-transformer-merges-tokens-before-deciding-what-set-to-exclude

### PR DESCRIPTION
**Pull request by swordEdge**

### CODE REVIEW

**Review by LiamMartens — CHANGES_REQUESTED** [review]
@swordEdge looks fine, just need to update the test

**Comment by six7** [comment]
@swordEdge updating expected test outputs is the wrong way. Why would we want those tests to all be failedToResolve??

**Comment by swordEdge** [comment]
> @swordEdge updating expected test outputs is the wrong way. Why would we want those tests to all be failedToResolve??

@six7 Is it wrong? I just excluded all token sets  represented on excludes token sets before merge tokens.
This is why it is not resolved.

**Comment by six7** [comment]
Yes. I would not change existing tests. I would add an additional test that does what is described in the issue. And then i'd try to make this new test not fail, plus existing ones not fail without changing them.

**Comment by six7** [comment]
@swordEdge let's pause this one for now - all other issues are more important than this one.

**Comment by thomasmattheussen** [comment]
I've tested this change in our setup and this seems to do what we expect!

**Comment by thomasmattheussen** [comment]
> I've tested this change in our setup and this seems to do what we expect!

It seems I spoke too soon. I'm still getting a bunch of `failedToResolve` after transforming in our setup.

**Comment by thomasmattheussen** [comment]
The original issue https://github.com/six7/figma-tokens/issues/1182 seems fixed by https://github.com/six7/figma-tokens/pull/1418

**Comment by six7** [comment]
> The original issue #1182 seems fixed by #1418

Thank you, can confirm it is fixed - added tests for it as well now.

**Pull request closed without merging**
