### PR TITLE
Creating annotations from the inspector

### PR DESCRIPTION
**Pull request by WardMe**
It wasn't clear for our developers which tokens were applied to which parts of our components. So I've created a simple way of adding the tokens linked to the selected layer. WDYT?

https://user-images.githubusercontent.com/3016302/150413092-36fe062b-3ecf-4b1b-b6eb-e4d0557e7d82.mov

### CODE REVIEW

**Comment by WardMe** [comment]
@six7 what do you think of this solution?

**Comment by six7** [comment]
This looks great! I didn't find the time yet to review this, hopefully sometime this week! But I love it. As I'm currently reworking the Inspector to also allow Multi inspecting I'll try to see how we can fit this in with the new concept before we'd ship this but rather ship it in pair. I'll let you know!

Thank you for this already! ❤️

**Comment by six7** [comment]
This is awesome, Ward! I've just merged a major PR so there's some merge conflicts. I can take a look at those for you, thank you for this already. I'll merge and release this over the weekend 👍

**Comment by six7** [comment]
Created a new PR based on yours to include the merge changes, will close this one.

I'll ship this with some other smaller features tomorrow.

Thanks!

**Pull request closed without merging**
